services:
  mysql:
    image: mysql:9.4.0
    container_name: shopping-cart-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 53cret
      MYSQL_DATABASE: cart
      MYSQL_USER: yu71
      MYSQL_PASSWORD: 53cret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    container_name: shopping-cart-maildev
    ports:
      - "1080:1080"  # Web UI
      - "1025:1025"  # SMTP
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 1080

volumes:
  mysql_data:
    driver: local